= Kas-Box Sürüm Geçmiş
:icons: font
:toc: left

== Sürüm No : 3.0.16.0620.5710
* Ödeme Ön Bildirimi (H14) mesajı eklendi.
* Muhabirlik Ödemesi (K14) mesajına Ön Bildirim Referansı alanı eklendi.
* Müşteri Ödemesi mesajlarındaki İşlem Ek Bilgisi bölümünde yer alan İşlem Ek Bilgisi alanı kaldırılarak Alt Kurum Müşteri Bilgileri grubu eklenmiştir.
* Add-on olarak, Entegrasyon tabloları olan TO_KAS ve FROM_KAS tablolarına mesajın Giriş Zamanı, İşlem Zamanı, Gönderilme Zamanı eklendi.
* Add-on olarak, TCMB KAS Arşiv ekranına mesajın Giriş Zamanı, İşlem Zamanı, Gönderilme Zamanı eklendi.


== Sürüm No : 3.0.16.0415.5650

* NYS Bildirimi (H07) ve Katılımcıya NYS Bildirimi(H08) mesajları eklendi.
* Gelen Entegrasyon ve Giden Entegrasyon servisleri silinerek bu servislerin yapmış olduğu işlemler ilgili mesaj servislerine aktarıldı. Böylelikle mesajların daha kısa sürede gönderilip, gelen mesajların entegrasyona daha kısa sürede bildirilmesi sağlandı.
* Entegrasyon iyileştirmeleri kapsamında, TO_KAS tablosundaki KAS_ISLTUR alanı zorunlu yapıldı.
* Katılımcılardan alınan geri dönüşler doğrultusunda, TO_KAS tablosu üzerinden yapılan sorgu entegrasyonu özelliği kaldırıldı.
* Sorgu servisine, parametrik olarak, otomatik mesaj durum sorgusu özelliği eklendi. (Detaylı bilgi için Global Bilişim ile iletişime geçebilirsiniz.)
* Otomatik mesaj durum sorgusuna, parametrik olarak, entegrasyona bildirim özelliği eklendi. (Detaylı bilgi için Global Bilişim ile iletişime geçebilirsiniz.)
* Kas-Box önyüzde, otomatik mesaj durum sorgusu kullanıldığında, giden mesajların işlenme ve karşı bankaya gönderilme zamanlarının mesaj üzerinde gösterilmesi sağlandı.
* Veritabanı erişiminde ve tablolarda iyileştirmeler yapıldı.


== Sürüm No : 2.1.15.0812.5100

* ADUP-4 değişiklikleri kapsamında, ADUP ekranlarında gerekli güncellemeler yapıldı.
* Session-timeout süresinin, kullanıcı Kas-Box a giriş yapıp ekranlara girmediği durumda uygulanmaması ile ilgili bir sorun giderildi.


== Sürüm No : 2.1.15.0401.4850

* TCMB, TLSv1.2 geçişi kapsamında, önyüz, servis kodu ve kullanılan kütüphaneler, Java 8’e uyumlu olacak şekilde güncellendi.
* Başarısız kullanıcı girişleri loglandı.
* Add-on olarak, mesaj giriş ekranlarına, banka müşteri bilgilerinin (statik olarak) eklenebilmesi ve mesaj alanlarına map edilmesi özelliği eklendi.


== Sürüm No : 2.1.14.1016.4515

* Ana Menü’ye mesaj sayıları ile ilgili bilgiler eklendi.
* Banka Bilgileri’ne günlük Banka-Şube değişikliklerinin görülebileceği bir ekran eklendi.
* Katılımcı Ödemesi (K12) mesajında Alıcı Hesap Numarası alanı için Alıcı Şube Kodu boş veya 90001 ise IBAN, 90001 ise zorunlu olma durumu eksikliği giderildi.
* Kullanıcı silme işlemi sorunu giderildi.
* Gelen mesajlardaki tarih alanlarının hatalı olması durumunda da mesajın alınması sağlandı.
* İBS Hesap Özeti Sorgulama ekranındaki Ekstre Satırı bölümüne Dekont Açıklama alanı eklendi.
* İBS Hesap Özeti Sorgulama ekranında Şube Kodu alanının yanına Şube Adı da eklendi.
* İBS Hesap Özeti Sorgulama ekranında Yeni İstek girişinde hesap numarasının detayları eklendi.
* İBS SSL sertifika dosyası olmadan bağlantı yöntemine geçildi.


== Sürüm No : 2.1.14.0530.4350

* BaSub İzleme ekranında TCMB’den gelen sonuç kodu gösterildi.
* BaSub İzleme ekranının takılma problemi giderildi.
* İBS Hesap Özeti Sorgulama ekranının takılma problemi giderildi.


== Sürüm No : 2.1.14.0513.4300

* Add-on olarak, TCMB İnternet Bankacılığı Sistemi (İBS) eklendi.
* Add-on olarak, İBS sistemi kullanılarak ekstre dosyasının (SWIFT MT940) oluşturulması eklendi.
* Katılımcı Piyasa İşlemleri (H03) işlem türü,  Para Piyasası TL Depo ve GİL İşlemi mesajında isteğe bağlı alan olan Faiz Oranı alanı zorunlu alan olarak güncellendi.
* Muhabirlik Ödemesi (K14) mesajına Aracı Kurum Hesap Numarası, İşlem Referansı, Gönderilen SWIFT Mesajı Durumu alanları eklendi.
* İhale Teklifi (H05) mesajında Teklif Türü alanına 4 - İhale Sonrası Satış eklendi.
* Önyüzden mesaj girişlerinde tutar alanlarının formatlı görünmesi sağlandı.
* Önyüzden mesaj girişlerinde tutar alanlarındaki ondalık ayraç nokta yerine virgül ile değiştirildi.
* Günsonunda gitmemiş olan mesajların işlem sırası öne alındı.
* TO_KAS tablosunda MTRN alanının boş olma durumu kontrol edildi.
* Kullanıcı mail adres zorunluluğu Oturum Açma Türü koşuluna bağlandı.
* Hızlı İade’de Açıklama alanının boş geçilmesi durumunda mesajın hata alma durumu giderildi.


== Sürüm No : 2.0.14.0114.4000

* Katılımcı Piyasa İşlemleri (H03) işlem türüne APİ Kotasyon Teklifi ve Para Piyasası TL Depo ve GİL İşlemi mesajları eklendi.
* TCMB Piyasa İşlemleri (H04) işlem türüne Para Piyasası TL Depo ve GİL Geri Bildirimi mesajı ekledi.
* Mesaj Geçmiş ekranına mesaj hakkında daha fazla detay eklendi.
* Listeyi aktar seçenekleri güncellendi, ön izleme kaldırıldı, yazdırma işlemi yetkiye bağlandı.
* Sorgu detay listesine aktarım butonu eklendi.
* Arşiv ekranındaki mesajlarda banka kodunun yanına banka adı da eklendi.
* Çıkış işlemlerindeki kullanıcının askıda kalmaması için önlem alındı.

* Add-on olarak Çift aşamalı giriş eklendi. (Gerekli bilgi için Global Bilişim ile iletişime geçebilirsiniz.)


== Sürüm No : 2.0.13.1008.3855

* Bulunan hatalar giderildi.
* Servis Tanımlarına tüm servisleri durdurup, başlatabilme özelliği eklendi.
* Arşiv Mesajlarında tutarların formatlı görünmesi sağlandı.
* Arşiv Mesajlarına Mesaj Geçmişi eklendi.
* K ve M mesajlarındaki Tutar alanına sıfır girilemez kontrol eklendi.
* EMKT mesajları gönderildiğinde sorgulama yapılarak varlıkların güncellenmesi sağlandı.
* Arşiv Mesajlarında B90 ve K18 mesajlarının görüntülenememe sorunu giderildi.
* Günsonu yapılırken gösterilen uyarı mesajları geliştirildi.
* Kullanıcı Yetkileri Rapor ekranı eklendi (Görüntülenebilmesi için yetki verilmesi gerekmektedir).
* Listeyi Aktar butonuna Yazıcı seçeneği eklendi.


== Sürüm No : 2.0.13.0820.3760

* Ana menü değiştirildi, verilerin alınması hızlandırıldı.
* Servislerin istenilen zaman aralıklarında, istenilen periyotlarda çalışma özelliği eklendi. (Servis Çalışma Periyot ekranına yetki verilmesi gerekmektedir)
* K14 mesajı için Hızlı İade seçeneği eklendi.
* Mesaj yazdırma işleminde sadece mesajı yazdıracak şekilde değiştirildi.
* Mesaj ekranlarının gelmesindeki hız ile ilgili iyileştirilmeler yapıldı.
* Programdan çıkış ile yaşanılan kilitlenme ve askıda kalma sorun giderildi.
* Servislerin start / stop işlemleri hızlandırıldı.
* Validasyon, Geri Besleme ve Statü Güncelleme servisleri kaldırıldı.
* Sorgu servisleri tek bir servis altında birleştirildi.


== Sürüm No : 2.0.13.0719.3650
* Performans iyileştirmesi yapıldı.

== Sürüm No : 2.1.13.0717.3635

* Apache Tomcat yerine Yeni Önyüz servisi kullanılmaya başlanıldı.
* Ana Menüdeki bakiye ve servis durumu güncelleştirmeleri ayrıldı.
* Ana Menüde Bekleyen Mesaj olması durumunda alan kırmızı renk yapıldı.
* Günsonu yapılana kadar bakiye bilgilerinin kaybolmaması sağlandı.
* D06 veya D07 mesajı geldiğinde otomatik Kıymet Varlık Bilgisi sorgusu yapılması sağlandı.
* Arşive gelen olarak yazılan gönderilmiş mesajların doğru statüde yazılması sağlandı.
* Günsonu dosyaları ile gelen mesajlarda parametre bilgilerinin değiştirilmesi eklendi.
* Entegrasyona bildirilen hata mesajlarındaki eksik açıklamalar eklendi.
* Arşiv araması için arama bilgilerinin otomatik gelmesi eklendi.

== Sürüm No : 2.0.13.0712.3600

·        KAS 2.0 üretim ortamı geçişi.

== Sürüm No : 2.0.13.0627.3550

* İyileştirmeler yapıldı.
* Bulunan hatalar giderildi.

== Sürüm No : 2.0.13.0612.3515

* 10 Haziran’da yayınlanan şemalara göre güncellemeler yapıldı.
* ADUP-3 entegre edildi.

== Sürüm No : 2.0.13.0530.3500

* Yeni şemalara göre güncellemeler yapıldı.
* Bekleyen onay sayısı hatası giderildi.

== Sürüm No : 2.0.13.0522.3450

* İyileştirmeler yapıldı.

== Sürüm No : 2.0.13.0514.3400

* İyileştirmeler yapıldı.
* Bulunan hatalar giderildi.
* Katılımcı Bilgilerindeki Sonraki İşgünü ve Günbaşı zamanı alanlarının değiştirilebilmesi sağlandı.


== Sürüm No : 2.0.13.0508.3350

* İyileştirmeler yapıldı.


== Sürüm No : 2.0.13.0502.3320

* Mesaj yapılarında bulunan farklılıklar güncellendi.


== Sürüm No : 2.0.13.0430.3300

* TCMB tarafından yayınlanan yeni xsd dosyaları güncellendi.


== Sürüm No : 2.0.13.0425.3200

·        KAS 2.0 sistemi için oluşturulan sürüm.


== Sürüm No : R_1.0.13.0201.2670

KAS-BOX Önyüzde yapılan değişiklikler:

* Bazı durumlarda hızlı iadede oluşan sorun giderildi.
* Ana menüdeki Bekleyen Mesaj Sayısı ve Tutarı eğer 0’dan büyükse kırmızı olacak şekilde renklendirildi.
KAS-BOX Servislerinde yapılan değişiklikler:

* Sorgu mesajları günlük olarak temizlenmesi eklendi.



== Sürüm No : R_1.0.12.1231.2525

KAS-BOX Önyüzde yapılan değişiklikler:

·        Bugfix.



== Sürüm No : R_1.0.12.1219.2500

KAS-BOX Önyüzde yapılan değişiklikler:

·        Ana Menüye Borçlandırılan, Alacaklandırılan, Bekleyen Mesaj Sayısı ve Tutarları eklendi.

·        Sorgu ekranı değiştirildi.

·        TCMB KAS Arşiv Sorgulama ekranı eklendi.

·        Tüm Mesajlar, Mesaj Onayları, Gönderim Onayı ve Adet-Tutar Rapor ekranlarına Mesaj Türü eklendi.

·        Hızlı İade için iyileştirmeler yapıldı.

KAS-BOX Servislerinde yapılan değişiklikler:

* Günsonu zamanından 5 dakika önce servislerin Bekleme Süresi 5 saniye olacak şekilde güncellendi.



== Sürüm No : R_1.0.12.1202.2400

KAS-BOX Önyüzde yapılan değişiklikler:

·        Günsonu işlemleri için rapor eklendi.

·        Excel’e aktarım için format seçeneği sunuldu.

·        Değişiklik bekliyor statüsündeki mesajların İptal edilebilmesi sağlandı.

KAS-BOX Servislerinde yapılan değişiklikler:

* TCMB KAS Mutabakat tablosu eklendi.

* TCMB KAS Arşiv tablosu eklendi.

* TCMB’den gelen günsonu, alınmış, işlenmiş, alınmamış ve işlenmemiş mesajlar dosyaları işlendi.



== Sürüm No : R_1.0.12.1126.2317

KAS-BOX Önyüzde yapılan değişiklikler:

·        ADUP işlemleri eklendi.

KAS-BOX Servislerinde yapılan değişiklikler:

* ADUP servisi eklendi.



== Sürüm No : R_1.0.12.1122.2222

KAS-BOX Önyüzde yapılan değişiklikler:

·        Giden ödeme mesajları için “Hızlı İade İsteği” fonksiyonu eklendi.

* Günsonu işlemlerindeki sorun giderildi.

KAS-BOX Servislerinde yapılan değişiklikler:

* Entegrasyon mesajlarıyla ilgili düzenlemeler yapıldı.




== Sürüm No : R_1.0.12.1121.2201

KAS-BOX Önyüzde yapılan değişiklikler:

* Gelen ödeme mesajları için “Hızlı İade” fonksiyonu eklendi.

* Günsonu işlemlerinde günsonu dosyalarının olması zorunlu olmaktan çıkarıldı, uyarı eklendi.

* Günsonu sayım dosyası ekranında mesaj adet farklılıkları renklendirildi.

KAS-BOX Servislerinde yapılan değişiklikler:

* Entegrasyon mesajlarıyla ilgili düzenlemeler yapıldı.

* TCMB’ye giden ve gelen imzalı mesajların loglanması sağlandı.

·        Günsonu işlemlerinde dosyalarla ilgili iyileştirmeler yapıldı.



== Sürüm No : R_1.0.12.1118.2162

KAS-BOX Önyüzde yapılan değişiklikler:

* Günsonu işlemlerine alınmamış mesaj dosyası kontrolü eklendi.

* Raporlar menüsüne aşağıdaki raporlar eklendi.,

o   Mesaj Adet ve Tutar Raporu

o   Kullanıcı İşlem Geçmişi

o   Kullanıcı Tanım Onay Raporu

o   Parametre Onay Raporu

* Mesajlar menüsü altına “Taslak Mesajlar” ekranı eklendi.

* Bütün mesaj ekranları ve “Tüm Mesajlar” akranlarına “Taslak Kaydet” düğmesi eklendi.

* Yardım dosyası HTML formatına çevrildi.

KAS-BOX Servislerinde yapılan değişiklikler:

* Şifreli olarak yayınlanan, sayım, işlenmemiş ve alınmamış mesaj dosyalarının otomatik olarak işlenmesi sağlandı.



== Sürüm No : R_1.0.12.1101.2000

KAS-BOX Önyüzde yapılan değişiklikler:

* Günsonu işlemleri için ekran eklendi.

* Sorgu ekranı genişletildi.

* Fazla kayıt olan listelere mesaj sayısı ve toplam tutarın gelmesi sağlandı.

* Yardım dokümanı eklendi (Yardım butonu).

KAS-BOX Servislerinde yapılan değişiklikler:

* Gelen ve giden entegrasyon servisleri çoklu çalışma yapısına çevrildi.

* ID alanı MTRN’den oluşturulacak şekilde değiştirildi

* TCMB’nin yayınladığı xsd dosyaları değiştirildi

* Tüm servislerin kontrolünü sağlayan Kontrol Servisi eklendi.




== Sürüm No : R_1.0.12.1018.1895

KAS-BOX Önyüzde yapılan değişiklikler.

* Performans iyileştirmeleri

KAS-BOX Servislerinde yapılan değişiklikler

* Performans iyileştirmeleri



== Sürüm No : R_1.0.12.1016.1861

KAS-BOX Önyüzde yapılan değişiklikler.

* Parametre onaylarında düzenlemeler

KAS-BOX Servislerinde yapılan değişiklikler

* TCMB Performans testleri için servis iyileştirmeleri



== Sürüm No : R_1.0.12.1012.1850

KAS-BOX Önyüzde yapılan değişiklikler.

* Veritabanı bağlantı yönetimi (pooling) iyileştirmeleri

* ID/Sorgu Numarası alımında performans iyileştirmeleri

KAS-BOX Servislerinde yapılan değişiklikler

* Veritabanı bağlantı yönetimi (pooling) iyileştirmeleri

* 09/10/2012 tarihli TCMB testlerinde karşılaşılan mesaj alım/gönderim hatalarına ilişkin güncellemeler



== Sürüm No : R_1.0.12.1009.1815

KAS-BOX Önyüzde yapılan değişiklikler.

* Performans testi için çoklu mesaj girişi imkanı sağlandı (Sadece TEST ortamı)

* Ana Menüde Ortam Türü (PROD/TEST) bilgisi eklendi

* Ana Menüde kullanıcı bilgileri kaldırıldı. (Ana Menü toolbar’da bulunan “Kullanıcı” etiketine tıklanıp detaylar görülebilir)

* Ana Menüde “Servis Bilgileri” ekranına “Kas-Box Windows” eklendi. Buradan servislerin sunucu üzerinde durumu gözlenebilir.

* Bazı mesajlarda zorunlu alan kontrolleri düzeltildi.

* IBAN kontrolü düzeltildi.

* OpenLDAP desteği eklendi.

* server.properties dosyası içinde bulunan açık şifre tanımları iptal edildi.

* Kullanıcı ekranında “Oturum Bilgilerini Sıfırla” özelliği onay işleminden çıkarıldı.

* Apache Tomcat restart sonrası sistemde bulunan tüm kullanıcı oturum bilgileri otomatik sıfırlandı.

KAS-BOX Servislerinde yapılan değişiklikler

* Gün sonu saati 17:45 e alındı.

* Bazı mesajlarda alınan “HASH Hatası” düzeltildi.

* Entegrasyon mesajları okuma ve yazma performansına yönelik iyiliştirmeler yapıldı.

* Sorgu mesajları ve Bakiye güncellemede yaşanan sorunlar giderildi.

* Apache Tomcat servisi için günsonuna restart eklendi.

* Gelen/Giden Entegrasyon 1. Tip için düzeltmeler yapıldı.

* Gün sonu saati 17:45 e alındı.



== Sürüm No : R_1.0.12.1002.1764

KAS-BOX Önyüzde yapılan değişiklikler.

* Hash doğrulama hatası ile ilgili düzenlemeler

* Ana Menüde KAS Servis Durumunun güncellenmesi ile ilgi düzenlemeler

* Ana Menüde Geçerli  iş Günü bilgisinin güncellenmesi ile ilgi düzenlemeler

* Ana Menüde Kullanıcı Bilgilerinin güncellenmesi ile ilgi düzenlemeler

* Gün Sonu Sayac dosyasının işlenmesi  ile ilgili düzenlemeler

* Kullanıcı Ve Rol tanımlamaları ile ilgili güncellemeler

* Kulanıcı kodunda kullanılabilecek karakter seti ile ilgili düzenlemeler

* Kullanıcı oturum bilgilerinin temizlenmesi ile ilgili düzenlemeler

* Yönlendirme Parametreleri ile ilgili düzenlemeler

KAS-BOX Servislerinde yapılan değişiklikler

* Gün sonu ve gün başı işlemleri ile ilgili düzenlemeler
